FROM python:3.11-slim

WORKDIR /app

COPY backend/pyproject.toml backend/ .
RUN pip install --upgrade pip && pip install poetry && poetry config virtualenvs.create false && poetry install --no-root

COPY backend/src ./src
COPY backend/alembic ./alembic
COPY backend/alembic.ini .
COPY backend/docker-entrypoint.sh ./docker-entrypoint.sh
RUN chmod +x ./docker-entrypoint.sh

CMD ["./docker-entrypoint.sh"]
