FROM node:20

WORKDIR /app

COPY frontend/package.json frontend/yarn.lock ./
RUN yarn install --frozen-lockfile

COPY frontend ./frontend
WORKDIR /app/frontend

CMD ["yarn", "dev", "--hostname", "0.0.0.0", "--port", "3000"]
