"""Gemini API client for doodle-to-attribute inference."""
from __future__ import annotations

import json
from typing import Any

import httpx
from pydantic import BaseModel, Field, ValidationError


class GeminiError(RuntimeError):
    """Raised when Gemini API fails."""


class GeminiAttributes(BaseModel):
    element: str = Field(default="fire")
    hp: int = Field(default=200, ge=50, le=500)
    base_attack: int = Field(default=50, ge=5, le=100)
    skill_type: str = Field(default="weapon")
    explanation: str = Field(default="Generated by Gemini")


class GeminiClient:
    def __init__(self, api_key: str, model: str) -> None:
        self._api_key = api_key
        self._model = model
        self._base_url = "https://generativelanguage.googleapis.com/v1beta"
        self._client = httpx.Client(timeout=40)

    def generate_attributes(self, strokes: list[dict[str, Any]], seed: int) -> dict[str, Any]:
        body = {
            "contents": [
                {
                    "role": "user",
                    "parts": [
                        {
                            "text": self._prompt(strokes, seed),
                        }
                    ],
                }
            ],
            "generationConfig": {
                "temperature": 0.2,
                "topP": 0.95,
                "topK": 32,
            },
        }

        url = f"{self._base_url}/models/{self._model}:generateContent"
        response = self._client.post(url, params={"key": self._api_key}, json=body)
        if response.status_code >= 400:
            raise GeminiError(f"Gemini error {response.status_code}: {response.text}")
        payload = response.json()
        text = (
            payload.get("candidates", [{}])[0]
            .get("content", {})
            .get("parts", [{}])[0]
            .get("text", "")
        )
        return self._parse_attributes(text, seed)

    def _prompt(self, strokes: list[dict[str, Any]], seed: int) -> str:
        return (
            "You rate drawn monsters for a deterministic AI battle game. "
            "Respond ONLY with compact JSON containing keys "
            'element, hp, base_attack, skill_type, explanation. '
            "hp must be 50-500, base_attack 5-100. "
            f"Seed: {seed}. Stroke summary: {strokes[:40]}"
        )

    def _parse_attributes(self, text: str, seed: int) -> dict[str, Any]:
        cleaned = self._strip_fence(text)
        try:
            attrs = GeminiAttributes.model_validate_json(cleaned)
        except ValidationError as exc:
            raise GeminiError(f"Gemini output invalid: {cleaned}") from exc
        except json.JSONDecodeError as exc:
            raise GeminiError(f"Gemini output not JSON: {cleaned}") from exc

        return {
            "element": attrs.element,
            "hp": max(50, min(500, int(attrs.hp))),
            "base_attack": max(5, min(100, int(attrs.base_attack))),
            "skill_type": attrs.skill_type or "weapon",
            "seed": seed,
            "explanation": attrs.explanation,
        }

    def _strip_fence(self, text: str) -> str:
        stripped = text.strip()
        if stripped.startswith("```"):
            lines = stripped.splitlines()
            if len(lines) >= 2:
                if lines[0].startswith("```"):
                    lines = lines[1:]
                if lines and lines[-1].startswith("```"):
                    lines = lines[:-1]
                stripped = "\n".join(lines)
            else:
                stripped = stripped.strip("`")
        return stripped.strip()
